config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "user/omniauth_callbacks",
    registrations: "user/registrations",
    sessions: "user/sessions"
  }

  get "/dramas/search" => "dramas#search", :as => :drama_search

  resources :dramas

  root to: "visitors#index"

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  belongs_to :user
  belongs_to :drama
end

app/models/drama.rb
class Drama < ActiveRecord::Base
  has_many :collections
  has_many :dramas, through: :collections

  def self.get_drama(id)
    TVDB.build_drama(id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable
  devise :registerable
  devise :recoverable
  devise :rememberable
  devise :trackable
  devise :validatable
  devise :omniauthable
  devise omniauth_providers: [:facebook]

  has_many :collections
  has_many :dramas, through: :collections

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end
end

app/models/user_drama.rb
class UserDrama < ActiveRecord::Base
  belongs_to :user
  belongs_to :drama
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dramas_controller.rb
class DramasController < ApplicationController
  def index
    @dramas = Drama.all
  end

  def show
    @drama = Drama.find(params[:id])
  end

  def search
    @dramas = TVDB.search(params[:search])
    redirect_to root_path && flash[:error] = "No show found!" if @dramas.empty?
  end
end

app/controllers/user/confirmations_controller.rb
class User
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    def facebook
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
  end
end

app/controllers/user/passwords_controller.rb
class User
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/user/registrations_controller.rb
class User
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    before_action :configure_account_update_params, only: [:update]

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    # protected

    # You can put the params you want to permit in the empty array.
    def configure_sign_up_params
      devise_parameter_sanitizer.for(:sign_up) << :name
    end

    # You can put the params you want to permit in the empty array.
    def configure_account_update_params
      devise_parameter_sanitizer.for(:account_update) << :name
    end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/user/sessions_controller.rb
class User
  class SessionsController < Devise::SessionsController
    # before_filter :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # You can put the params you want to permit in the empty array.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.for(:sign_in) << :attribute
    # end
  end
end

app/controllers/user/unlocks_controller.rb
class User
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dramas/index.html.erb
<% Drama.all.each do |drama|%>
  <%= drama.name %>
<% end %>

app/views/dramas/search.html.erb
<div>
  <h2>Search for any Drama!</h2>

  <ul>
    <li>Name</li> 
    <li>Summary</li>
  </ul>

  <ul>
    <% @dramas.each do |drama| %>
      <li><%= link_to drama.name, drama_path(drama.id) %></li>
      <li><%= drama.summary %></li>
    <% end %>
  </ul>
</div>

app/views/dramas/show.html.erb
<div>
  <h1><%= @drama.name %></h1>
  <%=  image_tag @drama.image %>
</div>

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Home', root_path, :id => 'home' %></li>
  <li><%= link_to 'Profile', edit_user_registration_path, :id => 'user' %></li>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete', :id => 'signout' %></li>
</ul>
<% else %>
  <li><%= link_to 'Home', root_path, :id => 'home' %></li>
  <li><%= link_to 'Login', new_user_session_path, :id => 'signin' %></li>
  <li><%= link_to 'Join', new_user_registration_path, :id => 'signup' %></li>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectDramas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <%= render 'layouts/navigation' %>
  </header>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/visitors/index.html.erb
<div class="welcome">
  <h1>Welcome <%= current_user.name %>!</h1>

  <h1>Find a show</h1>

  <div class="search-drama">
    <%= form_tag(drama_search_path, method: "get") do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search" %>
    <% end %>
  </div>
<div>